"""empty message

Revision ID: 2bf00968ffed
Revises: 
Create Date: 2025-11-14 17:23:15.526986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf00968ffed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('registro_fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=True),
    sa.Column('ciudad', sa.String(length=150), nullable=True),
    sa.Column('pais', sa.String(length=50), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dni', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('mensaje', sa.String(length=300), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tienda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cif', sa.String(), nullable=False),
    sa.Column('nombre_tienda', sa.String(), nullable=False),
    sa.Column('descripcion_tienda', sa.String(length=300), nullable=False),
    sa.Column('categoria_principal', sa.String(), nullable=False),
    sa.Column('telefono_comercial', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=300), nullable=False),
    sa.Column('redes_sociales', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif'),
    sa.UniqueConstraint('logo_url'),
    sa.UniqueConstraint('telefono_comercial')
    )
    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('gastos_envio', sa.Float(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tienda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(), nullable=False),
    sa.Column('descripcion_producto', sa.String(length=300), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('categoria_producto', sa.String(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('dimensiones', sa.String(), nullable=False),
    sa.Column('imagenes', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tienda_id'], ['tienda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tienda.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resenas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrellas', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('respuestas', sa.Text(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resenas')
    op.drop_table('favoritos')
    op.drop_table('productos')
    op.drop_table('historial')
    op.drop_table('tienda')
    op.drop_table('notificaciones')
    op.drop_table('user')
    # ### end Alembic commands ###
